package Telas;

import ClassesBasicas.Compra;
import ClassesBasicas.ListaItens;
import ClassesBasicas.Produto;
import Dao.DaoListaItens;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_adicionar_itens extends javax.swing.JFrame {
       ArrayList<Produto> arrayProduto;
       DefaultTableModel model = new DefaultTableModel();
       ArrayList<ListaItens> l1 = new ArrayList<ListaItens>();
 
       
      
       
      
    /**
     * Creates new form jframe_adicionar_itens
     */
    public jframe_adicionar_itens() {
        initComponents();
        listarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_pesquisar_por = new javax.swing.JLabel();
        jTextFieldPesquisaProduto = new javax.swing.JTextField();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel_pesquisar_por1 = new javax.swing.JLabel();
        jButtonAdicionar = new javax.swing.JButton();
        jScrollPane_pesquisa = new javax.swing.JScrollPane();
        jTable_pesquisa = new javax.swing.JTable();
        jButton_pesquisar = new javax.swing.JButton();
        jButton_Atualizar = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 330));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 330));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_pesquisar_por.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_pesquisar_por.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_pesquisar_por.setText("Qtd item selecionado : ");
        getContentPane().add(jLabel_pesquisar_por);
        jLabel_pesquisar_por.setBounds(220, 210, 179, 22);
        getContentPane().add(jTextFieldPesquisaProduto);
        jTextFieldPesquisaProduto.setBounds(40, 50, 180, 30);
        getContentPane().add(jTextFieldQtd);
        jTextFieldQtd.setBounds(270, 240, 70, 30);

        jLabel_pesquisar_por1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_pesquisar_por1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_pesquisar_por1.setText("Pesquisar por tipo do produto:");
        getContentPane().add(jLabel_pesquisar_por1);
        jLabel_pesquisar_por1.setBounds(170, 10, 250, 22);

        jButtonAdicionar.setBackground(new java.awt.Color(187, 222, 242));
        jButtonAdicionar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonAdicionar.setForeground(new java.awt.Color(0, 0, 255));
        jButtonAdicionar.setText("OK");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionar);
        jButtonAdicionar.setBounds(260, 280, 90, 30);

        jTable_pesquisa.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTable_pesquisa.setForeground(new java.awt.Color(0, 0, 255));
        jTable_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo:", "Tipo:", "Descrição:", "Tamanho:", "Preço unitario:"
            }
        ));
        jTable_pesquisa.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_pesquisa.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_pesquisa.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane_pesquisa.setViewportView(jTable_pesquisa);

        getContentPane().add(jScrollPane_pesquisa);
        jScrollPane_pesquisa.setBounds(10, 90, 570, 110);

        jButton_pesquisar.setBackground(new java.awt.Color(187, 222, 242));
        jButton_pesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_pesquisar.setForeground(new java.awt.Color(0, 0, 255));
        jButton_pesquisar.setText("Pesquisar");
        jButton_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pesquisar);
        jButton_pesquisar.setBounds(240, 50, 130, 30);

        jButton_Atualizar.setBackground(new java.awt.Color(187, 222, 242));
        jButton_Atualizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Atualizar.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Atualizar.setText("Atualizar");
        jButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Atualizar);
        jButton_Atualizar.setBounds(390, 50, 120, 30);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(520, 10, 60, 60);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela3.png"))); // NOI18N
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, -30, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listarProduto(){
        
                try {
        Fachada fachada = new Fachada();
        Produto produto = new Produto();        
        arrayProduto = fachada.listarProduto();
        if (arrayProduto.size() == 0){
            JOptionPane.showMessageDialog(null, "Não existe este produto");
        }
        else{
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Código:","Tipo:","Cor:","Discrição:", "Tamanho:", "Preço unitário:"});
        for(Produto p : arrayProduto){
            model.addRow(new String[] {String.valueOf(p.getCodProduto()),p.getTipoProduto(),p.getCorProduto() , p.getDescricaoProduto(), p.getTamanhoProduto(), String.valueOf(p.getValorUnitarioProduto())});            
        }
        jTable_pesquisa.setModel(model);     
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
    
        }
        
    }
    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        jframe_tela_vendas formVenda = new jframe_tela_vendas();
        formVenda.dispose();
        formVenda.alteraModel(model);        
        formVenda.recebeLista(l1);
        formVenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
   
        
        try {
            if(jTable_pesquisa.getSelectedRow() > -1 ){               
            Produto p = arrayProduto.get(jTable_pesquisa.getSelectedRow());         
            ListaItens l = new ListaItens();
            if(jTextFieldQtd.getText() != null && jTextFieldQtd.getText().length() > 0 && Integer.parseInt(jTextFieldQtd.getText()) > 0 ){
               l.setQuantidade(Integer.parseInt(jTextFieldQtd.getText()));
               l.setPreco(p.getValorUnitarioProduto() * l.getQuantidade());
            l.setProduto(p);
            
            l1.add(l);           
            
            
        model.setColumnIdentifiers(new String[]{"Código:","Tipo:","Cor:","Descrição:", "Tamanho:","Quantidade:", "Preço unitário:", "Preço Total:"});
       
        model.addRow(new String[] {String.valueOf(p.getCodProduto()),p.getTipoProduto(),p.getCorProduto() , p.getDescricaoProduto(), p.getTamanhoProduto(), 
              String.valueOf(l.getQuantidade()),String.valueOf(p.getValorUnitarioProduto()), String.valueOf(l.getPreco())});            
       
        JOptionPane.showMessageDialog(null, "Adicionado com sucesso");
            }else{
                 JOptionPane.showMessageDialog(null, "Informe a quantidade maior que 0");
            }
            
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
        
      
    
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButton_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesquisarActionPerformed
        // TODO add your handling code here:
              try {
        Fachada fachada = new Fachada();
        Produto produto = new Produto();
        produto.setTipoProduto(jTextFieldPesquisaProduto.getText());
        arrayProduto = fachada.pesquisarProduto(produto);
        if (arrayProduto.size() == 0){
            JOptionPane.showMessageDialog(null, "Não existe este produto");
        }
        else{
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Código:","Tipo:","Cor:","Discrição:", "Tamanho:", "Preço unitário:"});
        for(Produto p : arrayProduto){
            model.addRow(new String[] {String.valueOf(p.getCodProduto()),p.getTipoProduto(),p.getCorProduto() , p.getDescricaoProduto(), p.getTamanhoProduto(), String.valueOf(p.getValorUnitarioProduto())});            
        }
        jTable_pesquisa.setModel(model);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
    
        }
        
    }//GEN-LAST:event_jButton_pesquisarActionPerformed

    private void jButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtualizarActionPerformed
        listarProduto();
        
    }//GEN-LAST:event_jButton_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_adicionar_itens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_adicionar_itens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_adicionar_itens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_adicionar_itens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_adicionar_itens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButton_Atualizar;
    private javax.swing.JButton jButton_pesquisar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_pesquisar_por;
    private javax.swing.JLabel jLabel_pesquisar_por1;
    private javax.swing.JScrollPane jScrollPane_pesquisa;
    private javax.swing.JTable jTable_pesquisa;
    private javax.swing.JTextField jTextFieldPesquisaProduto;
    private javax.swing.JTextField jTextFieldQtd;
    // End of variables declaration//GEN-END:variables
}
