package Telas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_tela_menu2 extends javax.swing.JFrame {

    /**
     * Creates new form jframe_tela_menu2
     */
    public jframe_tela_menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_produto = new javax.swing.JButton();
        jButton_vendedor = new javax.swing.JButton();
        jLabel_cadastrar = new javax.swing.JLabel();
        jButton_voltar = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(908, 720));
        setPreferredSize(new java.awt.Dimension(908, 720));
        getContentPane().setLayout(null);

        jButton_produto.setBackground(new java.awt.Color(187, 222, 242));
        jButton_produto.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jButton_produto.setForeground(new java.awt.Color(0, 0, 255));
        jButton_produto.setText("Produtos");
        jButton_produto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_produto);
        jButton_produto.setBounds(110, 240, 260, 220);

        jButton_vendedor.setBackground(new java.awt.Color(252, 182, 132));
        jButton_vendedor.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jButton_vendedor.setForeground(new java.awt.Color(255, 0, 0));
        jButton_vendedor.setText("Vendedor");
        jButton_vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vendedorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_vendedor);
        jButton_vendedor.setBounds(490, 240, 260, 220);

        jLabel_cadastrar.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_cadastrar.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cadastrar.setText("Cadastrar:");
        getContentPane().add(jLabel_cadastrar);
        jLabel_cadastrar.setBounds(370, 90, 180, 60);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(800, 30, 60, 60);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela2.jpg"))); // NOI18N
        jLabel_backgroud.setToolTipText("Voltar");
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, 0, 900, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_produtoActionPerformed
        
        jframe_tela_cad_produto cad_pod = new jframe_tela_cad_produto();
        cad_pod.setLocationRelativeTo(null);
        cad_pod.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_produtoActionPerformed

    private void jButton_vendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vendedorActionPerformed
       
        jframe_tela_cad_vendedor cad_ved = new jframe_tela_cad_vendedor();
        cad_ved.setLocationRelativeTo(null);
        cad_ved.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_vendedorActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed

        jframe_tela_menu1 menu_1 = new jframe_tela_menu1();
        menu_1.setLocationRelativeTo(null);
        menu_1.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_tela_menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_produto;
    private javax.swing.JButton jButton_vendedor;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cadastrar;
    // End of variables declaration//GEN-END:variables
}
