package Telas;

import ClassesBasicas.Produto;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_tela_cad_produto extends javax.swing.JFrame {

    /**
     * Creates new form jframe_tela_cad_produto
     */
    public jframe_tela_cad_produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tamanho_do_produto = new javax.swing.JLabel();
        jLabel_tipo_do_produto = new javax.swing.JLabel();
        jLabel_descrição_do_produto = new javax.swing.JLabel();
        jLabel_preço_initario_do_produto = new javax.swing.JLabel();
        jLabel_cor_do_produto = new javax.swing.JLabel();
        jTextField_tipo_do_produto = new javax.swing.JTextField();
        jTextField_tamanho_do_produto = new javax.swing.JTextField();
        jTextField_cor_do_produto = new javax.swing.JTextField();
        jTextField_preço_initario_do_produto = new javax.swing.JTextField();
        jTextField_descrição_do_produto = new javax.swing.JTextField();
        jButton_cadastrar_produto = new javax.swing.JButton();
        jButton_pesquisar_produto = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jLabel_cadastro_de_produto = new javax.swing.JLabel();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(908, 720));
        getContentPane().setLayout(null);

        jLabel_tamanho_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_tamanho_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_tamanho_do_produto.setText("Tamanho do produto:");
        jLabel_tamanho_do_produto.setToolTipText("Dititar em maiusculo");
        getContentPane().add(jLabel_tamanho_do_produto);
        jLabel_tamanho_do_produto.setBounds(180, 370, 250, 40);

        jLabel_tipo_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_tipo_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_tipo_do_produto.setText("Tipo do produto:");
        getContentPane().add(jLabel_tipo_do_produto);
        jLabel_tipo_do_produto.setBounds(180, 190, 190, 30);

        jLabel_descrição_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_descrição_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_descrição_do_produto.setText("Descrição do produto: ");
        getContentPane().add(jLabel_descrição_do_produto);
        jLabel_descrição_do_produto.setBounds(180, 240, 310, 40);

        jLabel_preço_initario_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_preço_initario_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_preço_initario_do_produto.setText("Preço unitario do produto R$:");
        getContentPane().add(jLabel_preço_initario_do_produto);
        jLabel_preço_initario_do_produto.setBounds(180, 430, 330, 50);

        jLabel_cor_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_cor_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cor_do_produto.setText("Cor do produto:");
        getContentPane().add(jLabel_cor_do_produto);
        jLabel_cor_do_produto.setBounds(180, 310, 220, 30);
        getContentPane().add(jTextField_tipo_do_produto);
        jTextField_tipo_do_produto.setBounds(360, 190, 340, 30);
        getContentPane().add(jTextField_tamanho_do_produto);
        jTextField_tamanho_do_produto.setBounds(410, 370, 290, 30);
        getContentPane().add(jTextField_cor_do_produto);
        jTextField_cor_do_produto.setBounds(350, 310, 350, 30);
        getContentPane().add(jTextField_preço_initario_do_produto);
        jTextField_preço_initario_do_produto.setBounds(500, 440, 200, 30);
        getContentPane().add(jTextField_descrição_do_produto);
        jTextField_descrição_do_produto.setBounds(410, 250, 290, 30);

        jButton_cadastrar_produto.setBackground(new java.awt.Color(187, 222, 242));
        jButton_cadastrar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_cadastrar_produto.setForeground(new java.awt.Color(0, 0, 255));
        jButton_cadastrar_produto.setText("Cadastrar produto");
        jButton_cadastrar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cadastrar_produto);
        jButton_cadastrar_produto.setBounds(190, 500, 240, 50);

        jButton_pesquisar_produto.setBackground(new java.awt.Color(252, 182, 132));
        jButton_pesquisar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_pesquisar_produto.setForeground(new java.awt.Color(255, 0, 0));
        jButton_pesquisar_produto.setText("Pesquisar produto");
        jButton_pesquisar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesquisar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pesquisar_produto);
        jButton_pesquisar_produto.setBounds(450, 500, 230, 50);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(800, 30, 60, 60);

        jLabel_cadastro_de_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_cadastro_de_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cadastro_de_produto.setText("Cadastro de produto");
        getContentPane().add(jLabel_cadastro_de_produto);
        jLabel_cadastro_de_produto.setBounds(340, 90, 270, 30);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela2.jpg"))); // NOI18N
        jLabel_backgroud.setToolTipText("Voltar");
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, 0, 900, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed

        jframe_tela_menu2 menu_2 = new jframe_tela_menu2();
        menu_2.setLocationRelativeTo(null);
        menu_2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_pesquisar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesquisar_produtoActionPerformed
        
        jframe_pesquisa_produto del_prod = new jframe_pesquisa_produto();
        del_prod.setLocationRelativeTo(null);
        del_prod.setVisible(true);        
        
    }//GEN-LAST:event_jButton_pesquisar_produtoActionPerformed

    private void jButton_cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_produtoActionPerformed
       
        try {
            Fachada fachada = new Fachada();
            Produto p = new Produto();
            p.setTipoProduto(jTextField_tipo_do_produto.getText());
            p.setDescricaoProduto(jTextField_descrição_do_produto.getText());
            p.setCorProduto(jTextField_cor_do_produto.getText());
            p.setTamanhoProduto(jTextField_tamanho_do_produto.getText());
            if(jTextField_preço_initario_do_produto.getText() != null && jTextField_preço_initario_do_produto.getText().length() > 0 ){
               p.setValorUnitarioProduto(Float.parseFloat(jTextField_preço_initario_do_produto.getText()));
            }
            fachada.cadastraProduto(p);
            JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton_cadastrar_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_tela_cad_produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar_produto;
    private javax.swing.JButton jButton_pesquisar_produto;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cadastro_de_produto;
    private javax.swing.JLabel jLabel_cor_do_produto;
    private javax.swing.JLabel jLabel_descrição_do_produto;
    private javax.swing.JLabel jLabel_preço_initario_do_produto;
    private javax.swing.JLabel jLabel_tamanho_do_produto;
    private javax.swing.JLabel jLabel_tipo_do_produto;
    private javax.swing.JTextField jTextField_cor_do_produto;
    private javax.swing.JTextField jTextField_descrição_do_produto;
    private javax.swing.JTextField jTextField_preço_initario_do_produto;
    private javax.swing.JTextField jTextField_tamanho_do_produto;
    private javax.swing.JTextField jTextField_tipo_do_produto;
    // End of variables declaration//GEN-END:variables
}
