package Telas;

import ClassesBasicas.Vendedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_pesquisa_vendedor extends javax.swing.JFrame {
     ArrayList<Vendedor> arrayVendedor; 
    /**
     * Creates new form jframe_deletar_vendedor
     */
    public jframe_pesquisa_vendedor() {
        initComponents();
        listarVendedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void listarVendedor(){
        try {
        Fachada fachada = new Fachada();
        Vendedor vendedor = new Vendedor();
        arrayVendedor = fachada.listarVendedor();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Codigo","CPF","Nome","Data nasc.", "Salario"});
        for(Vendedor v : arrayVendedor){
            model.addRow(new String[] {String.valueOf(v.getCodVendedor()),v.getCpfVendedor(),v.getNomeVendedor(), v.getDataNascVendedor(), String.valueOf(v.getSalario())});            
        }
        jTable_pesquisa.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
    
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_pesquisar_por2 = new javax.swing.JLabel();
        jButton_alterar = new javax.swing.JButton();
        jTextField_pesquisa = new javax.swing.JTextField();
        jButton_voltar = new javax.swing.JButton();
        jScrollPane_pesquisa = new javax.swing.JScrollPane();
        jTable_pesquisa = new javax.swing.JTable();
        jButton_Atualiza = new javax.swing.JButton();
        jButton_deletar = new javax.swing.JButton();
        jButton_pesquisar = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 330));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel_pesquisar_por2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_pesquisar_por2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_pesquisar_por2.setText("Pesquisar vendedor por nome : ");
        getContentPane().add(jLabel_pesquisar_por2);
        jLabel_pesquisar_por2.setBounds(160, 10, 270, 20);

        jButton_alterar.setBackground(new java.awt.Color(187, 222, 242));
        jButton_alterar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_alterar.setForeground(new java.awt.Color(0, 0, 255));
        jButton_alterar.setText("Alterar");
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_alterar);
        jButton_alterar.setBounds(160, 260, 130, 30);
        getContentPane().add(jTextField_pesquisa);
        jTextField_pesquisa.setBounds(60, 70, 180, 30);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(520, 10, 60, 60);

        jTable_pesquisa.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jTable_pesquisa.setForeground(new java.awt.Color(0, 0, 255));
        jTable_pesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo:", "CPF:", "Nome:", "Data de nasc.", "Comissão:", "Salário:"
            }
        ));
        jTable_pesquisa.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_pesquisa.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable_pesquisa.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane_pesquisa.setViewportView(jTable_pesquisa);

        getContentPane().add(jScrollPane_pesquisa);
        jScrollPane_pesquisa.setBounds(10, 120, 570, 110);

        jButton_Atualiza.setBackground(new java.awt.Color(187, 222, 242));
        jButton_Atualiza.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Atualiza.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Atualiza.setText("Atualizar");
        jButton_Atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtualizaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Atualiza);
        jButton_Atualiza.setBounds(400, 70, 130, 30);

        jButton_deletar.setBackground(new java.awt.Color(252, 182, 132));
        jButton_deletar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_deletar.setForeground(new java.awt.Color(255, 0, 0));
        jButton_deletar.setText("Deletar");
        jButton_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deletarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_deletar);
        jButton_deletar.setBounds(300, 260, 130, 30);

        jButton_pesquisar.setBackground(new java.awt.Color(187, 222, 242));
        jButton_pesquisar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_pesquisar.setForeground(new java.awt.Color(0, 0, 255));
        jButton_pesquisar.setText("Pesquisar");
        jButton_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pesquisar);
        jButton_pesquisar.setBounds(250, 70, 130, 30);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela3.png"))); // NOI18N
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, -30, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
      
        this.dispose();
        
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
       
       try {
            // TODO add your handling code here:
            if (jTable_pesquisa.getSelectedRow() > -1) {                
                Vendedor v = arrayVendedor.get(jTable_pesquisa.getSelectedRow());
                jframe_tela_atu_vendedor atu_vend = new jframe_tela_atu_vendedor(v);
               atu_vend.setVisible(true);
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Por favor selecionar uma linha ");
            }
          }
          catch(Exception e ) {
                     JOptionPane.showMessageDialog(rootPane, e.getMessage());
             }    
              
    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jButton_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deletarActionPerformed
        // TODO add your handling code here:
         try {
            if(jTable_pesquisa.getSelectedRow() > -1 ){
                Fachada fachada = new Fachada();
                Vendedor v = new Vendedor();
                v = arrayVendedor.get(jTable_pesquisa.getSelectedRow());
                fachada.deletarVendedor(v);
                JOptionPane.showMessageDialog(null, "Deletado com Sucesso");
            }
            else {
                JOptionPane.showMessageDialog(null, "Selecione uma linha");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Deletado com Sucesso");
        }
    }//GEN-LAST:event_jButton_deletarActionPerformed

    private void jButton_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesquisarActionPerformed
        // TODO add your handling code here:
        try {
        Fachada fachada = new Fachada();
        Vendedor vendedor = new Vendedor();
        vendedor.setNomeVendedor(jTextField_pesquisa.getText());
        arrayVendedor = fachada.pesquisarVendedor(vendedor);
        if (arrayVendedor.size() == 0){
            JOptionPane.showMessageDialog(null, "Não existe este vendedor");
        }
        else{
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Codigo","CPF","Nome","Data nasc.", "Salario"});
        for(Vendedor v : arrayVendedor){
            model.addRow(new String[] {String.valueOf(v.getCodVendedor()),v.getCpfVendedor(),v.getNomeVendedor(), v.getDataNascVendedor(), String.valueOf(v.getSalario())});            
        }
        jTable_pesquisa.setModel(model);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
    
        }
  
    }//GEN-LAST:event_jButton_pesquisarActionPerformed

    private void jButton_AtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtualizaActionPerformed
        // TODO add your handling code here:
        listarVendedor();
    }//GEN-LAST:event_jButton_AtualizaActionPerformed

  

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_pesquisa_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_pesquisa_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_pesquisa_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_pesquisa_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_pesquisa_vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Atualiza;
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_deletar;
    private javax.swing.JButton jButton_pesquisar;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_pesquisar_por2;
    private javax.swing.JScrollPane jScrollPane_pesquisa;
    private javax.swing.JTable jTable_pesquisa;
    private javax.swing.JTextField jTextField_pesquisa;
    // End of variables declaration//GEN-END:variables
}
