package Telas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_tela_menu1 extends javax.swing.JFrame {

    /**
     * Creates new form jframe_tela_menu1
     */
    public jframe_tela_menu1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_voltar = new javax.swing.JButton();
        jButton_ADM = new javax.swing.JButton();
        jButton_vendas = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(908, 720));
        setPreferredSize(new java.awt.Dimension(908, 720));
        getContentPane().setLayout(null);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(800, 30, 60, 60);

        jButton_ADM.setBackground(new java.awt.Color(252, 182, 132));
        jButton_ADM.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jButton_ADM.setForeground(new java.awt.Color(255, 0, 0));
        jButton_ADM.setText("ADM");
        jButton_ADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADMActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ADM);
        jButton_ADM.setBounds(490, 240, 260, 220);

        jButton_vendas.setBackground(new java.awt.Color(187, 222, 242));
        jButton_vendas.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jButton_vendas.setForeground(new java.awt.Color(0, 0, 255));
        jButton_vendas.setText("Vendas");
        jButton_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vendasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_vendas);
        jButton_vendas.setBounds(100, 240, 260, 220);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela2.jpg"))); // NOI18N
        jLabel_backgroud.setToolTipText("Voltar");
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, 0, 900, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        
         jframe_tela_inicial tela_p = new jframe_tela_inicial();
        tela_p.setLocationRelativeTo(null);
        tela_p.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vendasActionPerformed
      
        jframe_tela_vendas vendas = new jframe_tela_vendas();
        vendas.setLocationRelativeTo(null);
        vendas.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_vendasActionPerformed

    private void jButton_ADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADMActionPerformed
        
        jframe_tela_menu2 menu_2 = new jframe_tela_menu2();
        menu_2.setLocationRelativeTo(null);
        menu_2.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton_ADMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_tela_menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADM;
    private javax.swing.JButton jButton_vendas;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    // End of variables declaration//GEN-END:variables
}
