package Telas;

import ClassesBasicas.Vendedor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_tela_cad_vendedor extends javax.swing.JFrame {

    /**
     * Creates new form jframe_tela_cad_vendedor
     */
    public jframe_tela_cad_vendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_cadastro_de_vendedor = new javax.swing.JLabel();
        jTextFieldCpfVendedor = new javax.swing.JTextField();
        jLabelNomeVendedor = new javax.swing.JLabel();
        jTextFieldNomeVendedor = new javax.swing.JTextField();
        jLabelDataVendedor = new javax.swing.JLabel();
        jTextFieldDataVendedor = new javax.swing.JTextField();
        jLabelSalarioVendedor = new javax.swing.JLabel();
        jTextFieldSalarioVendedor = new javax.swing.JTextField();
        jButton_cadastrar_produto = new javax.swing.JButton();
        jButton_pesquisar_produto = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jLabelCpfVendedor = new javax.swing.JLabel();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(908, 720));
        setPreferredSize(new java.awt.Dimension(908, 720));
        getContentPane().setLayout(null);

        jLabel_cadastro_de_vendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_cadastro_de_vendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cadastro_de_vendedor.setText("Cadastro de vendedor");
        getContentPane().add(jLabel_cadastro_de_vendedor);
        jLabel_cadastro_de_vendedor.setBounds(340, 90, 270, 30);
        getContentPane().add(jTextFieldCpfVendedor);
        jTextFieldCpfVendedor.setBounds(350, 200, 380, 30);

        jLabelNomeVendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelNomeVendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelNomeVendedor.setText("Nome do vendedor:");
        getContentPane().add(jLabelNomeVendedor);
        jLabelNomeVendedor.setBounds(160, 250, 310, 40);
        getContentPane().add(jTextFieldNomeVendedor);
        jTextFieldNomeVendedor.setBounds(360, 260, 370, 30);

        jLabelDataVendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelDataVendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelDataVendedor.setText("Data de nasc. do vendedor:");
        getContentPane().add(jLabelDataVendedor);
        jLabelDataVendedor.setBounds(160, 320, 290, 30);

        jTextFieldDataVendedor.setToolTipText("Digitar a data neste formato: 10/10/2010");
        getContentPane().add(jTextFieldDataVendedor);
        jTextFieldDataVendedor.setBounds(450, 320, 280, 30);

        jLabelSalarioVendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelSalarioVendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelSalarioVendedor.setText("Salário do vendedor R$:");
        getContentPane().add(jLabelSalarioVendedor);
        jLabelSalarioVendedor.setBounds(160, 360, 330, 50);
        getContentPane().add(jTextFieldSalarioVendedor);
        jTextFieldSalarioVendedor.setBounds(420, 370, 310, 30);

        jButton_cadastrar_produto.setBackground(new java.awt.Color(187, 222, 242));
        jButton_cadastrar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_cadastrar_produto.setForeground(new java.awt.Color(0, 0, 255));
        jButton_cadastrar_produto.setText("Cadastrar vendedor");
        jButton_cadastrar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cadastrar_produto);
        jButton_cadastrar_produto.setBounds(220, 470, 240, 50);

        jButton_pesquisar_produto.setBackground(new java.awt.Color(252, 182, 132));
        jButton_pesquisar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_pesquisar_produto.setForeground(new java.awt.Color(255, 0, 0));
        jButton_pesquisar_produto.setText("Pesquisar vendedor");
        jButton_pesquisar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesquisar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pesquisar_produto);
        jButton_pesquisar_produto.setBounds(470, 470, 250, 50);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(810, 30, 60, 60);

        jLabelCpfVendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelCpfVendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCpfVendedor.setText("CPF do vendedor:");
        getContentPane().add(jLabelCpfVendedor);
        jLabelCpfVendedor.setBounds(160, 200, 190, 30);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela2.jpg"))); // NOI18N
        jLabel_backgroud.setToolTipText("Voltar");
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, 0, 900, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_pesquisar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesquisar_produtoActionPerformed
        
        
        jframe_pesquisa_vendedor del_vend = new jframe_pesquisa_vendedor();
        del_vend.setLocationRelativeTo(null);
        del_vend.setVisible(true);
        

    }//GEN-LAST:event_jButton_pesquisar_produtoActionPerformed

    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed

        jframe_tela_menu2 menu_2 = new jframe_tela_menu2();
        menu_2.setLocationRelativeTo(null);
        menu_2.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_produtoActionPerformed
        // TODO add your handling code here:
        try {
            Fachada fachada = new Fachada();
            Vendedor v = new Vendedor();
            v.setCpfVendedor(jTextFieldCpfVendedor.getText());
            v.setNomeVendedor(jTextFieldNomeVendedor.getText());
            v.setDataNascVendedor(jTextFieldDataVendedor.getText());
            if(jTextFieldSalarioVendedor.getText() != null && jTextFieldSalarioVendedor.getText().length() > 0 ){
               v.setSalario(Float.parseFloat(jTextFieldSalarioVendedor.getText()));
            }
            fachada.cadastraVendedor(v);
            JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton_cadastrar_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_cad_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_tela_cad_vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar_produto;
    private javax.swing.JButton jButton_pesquisar_produto;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabelCpfVendedor;
    private javax.swing.JLabel jLabelDataVendedor;
    private javax.swing.JLabel jLabelNomeVendedor;
    private javax.swing.JLabel jLabelSalarioVendedor;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cadastro_de_vendedor;
    private javax.swing.JTextField jTextFieldCpfVendedor;
    private javax.swing.JTextField jTextFieldDataVendedor;
    private javax.swing.JTextField jTextFieldNomeVendedor;
    private javax.swing.JTextField jTextFieldSalarioVendedor;
    // End of variables declaration//GEN-END:variables
}
