package Telas;

import ClassesBasicas.Compra;
import ClassesBasicas.ListaItens;
import ClassesBasicas.Pagamento;
import ClassesBasicas.TipoPagamento;
import Dao.DaoCompra;
import Dao.DaoListaItens;
import Dao.DaoPagamento;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class jframe_pagamento extends javax.swing.JFrame {
    boolean aceito = false; 
    Pagamento p = new Pagamento();
    ArrayList<TipoPagamento> arrayPagamento = new ArrayList<TipoPagamento>();
    ArrayList<ListaItens> listaItens; 
    jframe_tela_vendas formVendas = new jframe_tela_vendas();
    
    /**
     * Creates new form jframe_pagamento
     */
    public jframe_pagamento(ArrayList<ListaItens> lista) {
        listaItens = lista;
        initComponents();
        listarTipoPagamento();
        jTextFieldValorPagamento.setText(String.valueOf(calculaTotal()));
        
    }

   
    
    private void listarTipoPagamento() {
        try {
            Fachada fachada = new Fachada();      
            arrayPagamento = fachada.listarTipoPagamento();
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (TipoPagamento tipoPagamento : arrayPagamento) {
                model.addElement(tipoPagamento.getDescTipoPagamento());
            }
            jComboBoxFormPagamento.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }
    
    private void cadastrarPagamento(){
        try {
            Fachada fachada = new Fachada();            
            if(jTextFieldValorPagamento.getText() != null && jTextFieldValorPagamento.getText().length() > 0){                
            p.setValorPagamento(Float.parseFloat(jTextFieldValorPagamento.getText()));
            }
            p.setDataPagamento(jTextFieldDataPagamento.getText());
            fachada.cadastraPagamento(p);
            aceito = true;
            JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel__form_pagto1 = new javax.swing.JLabel();
        jComboBoxFormPagamento = new javax.swing.JComboBox<>();
        jTextFieldDataPagamento = new javax.swing.JTextField();
        jLabel__form_pagto2 = new javax.swing.JLabel();
        jTextFieldValorPagamento = new javax.swing.JTextField();
        jLabel_cod_vendedor2 = new javax.swing.JLabel();
        jButtonFinalizarCompra = new javax.swing.JButton();
        jButton_remover = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 330));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 330));
        getContentPane().setLayout(null);

        jLabel__form_pagto1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel__form_pagto1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel__form_pagto1.setText("Data : ");
        getContentPane().add(jLabel__form_pagto1);
        jLabel__form_pagto1.setBounds(210, 160, 80, 22);

        jComboBoxFormPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Avista", "Cartão 1X sem juros", "Cartão 2X sem juros", "Cartão 3X sem juros", "Cartão 4X sem juros", "Cheque" }));
        getContentPane().add(jComboBoxFormPagamento);
        jComboBoxFormPagamento.setBounds(210, 80, 160, 30);
        getContentPane().add(jTextFieldDataPagamento);
        jTextFieldDataPagamento.setBounds(290, 160, 80, 30);

        jLabel__form_pagto2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel__form_pagto2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel__form_pagto2.setText("Valor R$:");
        getContentPane().add(jLabel__form_pagto2);
        jLabel__form_pagto2.setBounds(210, 120, 80, 22);
        getContentPane().add(jTextFieldValorPagamento);
        jTextFieldValorPagamento.setBounds(290, 120, 80, 30);

        jLabel_cod_vendedor2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_cod_vendedor2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cod_vendedor2.setText("Forma de pagamento:");
        getContentPane().add(jLabel_cod_vendedor2);
        jLabel_cod_vendedor2.setBounds(210, 50, 200, 22);

        jButtonFinalizarCompra.setBackground(new java.awt.Color(187, 222, 242));
        jButtonFinalizarCompra.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonFinalizarCompra.setForeground(new java.awt.Color(0, 0, 255));
        jButtonFinalizarCompra.setText("Finalizar compra");
        jButtonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizarCompra);
        jButtonFinalizarCompra.setBounds(230, 210, 130, 30);

        jButton_remover.setBackground(new java.awt.Color(252, 182, 132));
        jButton_remover.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton_remover.setForeground(new java.awt.Color(255, 0, 0));
        jButton_remover.setText("Cancelar compra");
        jButton_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removerActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_remover);
        jButton_remover.setBounds(230, 250, 130, 30);

        jLabel_backgroud.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela3.png"))); // NOI18N
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, -50, 600, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarCompraActionPerformed
        
        cadastrarPagamento();
        if(aceito == true){         
            try {
                Fachada fachada = new Fachada();
                Compra c = new Compra();
                p.setCodPagamento(fachada.codigoPagamento());
                c.setPagamento(p);
                c.setCliente(formVendas.retornaCliente());
                c.setVendedor(formVendas.retornaVendedor());
                TipoPagamento tp = new TipoPagamento();
                tp = arrayPagamento.get(jComboBoxFormPagamento.getSelectedIndex());
                c.setTipoPagamento(tp);                
                fachada.cadastraCompra(c);
                c.setNfCompra(fachada.nfCompra());                 
                fachada.cadastraListaItens(listaItens);                
                JOptionPane.showMessageDialog(null, "Tudo certo");                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
         
          if(jComboBoxFormPagamento.getSelectedIndex() == 1){
          jframe_pgto_cartao formCartao = new jframe_pgto_cartao();
          formCartao.setVisible(true);
        }else if(jComboBoxFormPagamento.getSelectedIndex() == 2){
          jframe_pgto_cheque formCheque = new jframe_pgto_cheque();
          formCheque.setVisible(true);
        }
        this.dispose();
        }
        
        
        
        
     
        
    }//GEN-LAST:event_jButtonFinalizarCompraActionPerformed

    private void jButton_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removerActionPerformed
       
       this.dispose();
        
    }//GEN-LAST:event_jButton_removerActionPerformed
   
    public float calculaTotal(){
        float total = 0;
        if(listaItens != null){
           for (ListaItens l : listaItens) {
            total += l.getPreco();            
        }
           return total;
        }
        else{
            JOptionPane.showMessageDialog(null, "Lista Vazia");
            return total;
        }
          
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_pagamento(new ArrayList<ListaItens>()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizarCompra;
    private javax.swing.JButton jButton_remover;
    private javax.swing.JComboBox<String> jComboBoxFormPagamento;
    private javax.swing.JLabel jLabel__form_pagto1;
    private javax.swing.JLabel jLabel__form_pagto2;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cod_vendedor2;
    private javax.swing.JTextField jTextFieldDataPagamento;
    private javax.swing.JTextField jTextFieldValorPagamento;
    // End of variables declaration//GEN-END:variables
}
