package Telas;


import ClassesBasicas.Vendedor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author artin
 */
public class jframe_tela_atu_vendedor extends javax.swing.JFrame {
    Vendedor v ;
    
    /**
     * Creates new form jframe_tela_atu_vendedor
     */
    public jframe_tela_atu_vendedor(Vendedor vend) {
        initComponents();
        v = vend;
        jTextFieldCpfVendedor.setText(v.getCpfVendedor());
        jTextFieldNomeVendedor.setText(v.getNomeVendedor());
        jTextFieldDataVendedor.setText(v.getDataNascVendedor());
        jTextFieldSalarioVendedor.setText(String.valueOf(v.getSalario()));
        
        
    }

    jframe_tela_atu_vendedor() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_atualizar_vendedor = new javax.swing.JLabel();
        jLabel_tipo_do_produto1 = new javax.swing.JLabel();
        jTextFieldCpfVendedor = new javax.swing.JTextField();
        jLabel_descrição_do_produto = new javax.swing.JLabel();
        jTextFieldNomeVendedor = new javax.swing.JTextField();
        jTextFieldDataVendedor = new javax.swing.JTextField();
        jLabel_cor_do_produto = new javax.swing.JLabel();
        jLabel_preço_initario_do_produto = new javax.swing.JLabel();
        jTextFieldSalarioVendedor = new javax.swing.JTextField();
        jButton_cadastrar_produto = new javax.swing.JButton();
        jButton_pesquisar_produto = new javax.swing.JButton();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 680));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(890, 680));
        getContentPane().setLayout(null);

        jLabel_atualizar_vendedor.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_atualizar_vendedor.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_atualizar_vendedor.setText("Atualizar vendedor");
        getContentPane().add(jLabel_atualizar_vendedor);
        jLabel_atualizar_vendedor.setBounds(340, 90, 270, 30);

        jLabel_tipo_do_produto1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_tipo_do_produto1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_tipo_do_produto1.setText("CPF do vendedor:");
        getContentPane().add(jLabel_tipo_do_produto1);
        jLabel_tipo_do_produto1.setBounds(160, 200, 190, 30);
        getContentPane().add(jTextFieldCpfVendedor);
        jTextFieldCpfVendedor.setBounds(350, 200, 380, 30);

        jLabel_descrição_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_descrição_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_descrição_do_produto.setText("Nome do vendedor:");
        getContentPane().add(jLabel_descrição_do_produto);
        jLabel_descrição_do_produto.setBounds(160, 250, 310, 40);
        getContentPane().add(jTextFieldNomeVendedor);
        jTextFieldNomeVendedor.setBounds(360, 260, 370, 30);

        jTextFieldDataVendedor.setToolTipText("Digitar a data neste formato: 10/10/2010");
        getContentPane().add(jTextFieldDataVendedor);
        jTextFieldDataVendedor.setBounds(450, 320, 280, 30);

        jLabel_cor_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_cor_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cor_do_produto.setText("Data de nasc. do vendedor:");
        getContentPane().add(jLabel_cor_do_produto);
        jLabel_cor_do_produto.setBounds(160, 320, 290, 30);

        jLabel_preço_initario_do_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_preço_initario_do_produto.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_preço_initario_do_produto.setText("Salário do vendedor R$:");
        getContentPane().add(jLabel_preço_initario_do_produto);
        jLabel_preço_initario_do_produto.setBounds(160, 360, 330, 50);
        getContentPane().add(jTextFieldSalarioVendedor);
        jTextFieldSalarioVendedor.setBounds(420, 370, 310, 30);

        jButton_cadastrar_produto.setBackground(new java.awt.Color(187, 222, 242));
        jButton_cadastrar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_cadastrar_produto.setForeground(new java.awt.Color(0, 0, 255));
        jButton_cadastrar_produto.setText("Atualizar vendedor");
        jButton_cadastrar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cadastrar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cadastrar_produto);
        jButton_cadastrar_produto.setBounds(180, 450, 240, 50);

        jButton_pesquisar_produto.setBackground(new java.awt.Color(252, 182, 132));
        jButton_pesquisar_produto.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_pesquisar_produto.setForeground(new java.awt.Color(255, 0, 0));
        jButton_pesquisar_produto.setText("Cancelar");
        jButton_pesquisar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pesquisar_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_pesquisar_produto);
        jButton_pesquisar_produto.setBounds(460, 450, 250, 50);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela2.jpg"))); // NOI18N
        jLabel_backgroud.setToolTipText("Voltar");
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, 0, 890, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_pesquisar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pesquisar_produtoActionPerformed

         this.dispose();

    }//GEN-LAST:event_jButton_pesquisar_produtoActionPerformed

    private void jButton_cadastrar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cadastrar_produtoActionPerformed
        // TODO add your handling code here:
        
        try {
        Fachada fachada = new Fachada();
        v.setCodVendedor(v.getCodVendedor());
        v.setCpfVendedor(jTextFieldCpfVendedor.getText());
        v.setNomeVendedor(jTextFieldNomeVendedor.getText());
        v.setDataNascVendedor(jTextFieldDataVendedor.getText());
        if(jTextFieldSalarioVendedor.getText() != null && jTextFieldSalarioVendedor.getText().length() > 0){                
            v.setSalario(Float.parseFloat(jTextFieldSalarioVendedor.getText()));
        }        
            fachada.alterarVendedor(v);
            JOptionPane.showMessageDialog(null, "Atualizado com Sucesso !");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton_cadastrar_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_atu_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_atu_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_atu_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_tela_atu_vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_tela_atu_vendedor(new Vendedor()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cadastrar_produto;
    private javax.swing.JButton jButton_pesquisar_produto;
    private javax.swing.JLabel jLabel_atualizar_vendedor;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cor_do_produto;
    private javax.swing.JLabel jLabel_descrição_do_produto;
    private javax.swing.JLabel jLabel_preço_initario_do_produto;
    private javax.swing.JLabel jLabel_tipo_do_produto1;
    private javax.swing.JTextField jTextFieldCpfVendedor;
    private javax.swing.JTextField jTextFieldDataVendedor;
    private javax.swing.JTextField jTextFieldNomeVendedor;
    private javax.swing.JTextField jTextFieldSalarioVendedor;
    // End of variables declaration//GEN-END:variables
}
