package Telas;

import ClassesBasicas.Cartao;
import ClassesBasicas.Pagamento;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author artin
 */
public class jframe_pgto_cartao extends javax.swing.JFrame {
    boolean aceito = false;
    
    /**
     * Creates new form jframe_pgto_cartao
     */
    public jframe_pgto_cartao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_numero_cartao = new javax.swing.JLabel();
        jTextField_numero_cartao = new javax.swing.JTextField();
        jButton_Confirmar_dados = new javax.swing.JButton();
        jButton_voltar = new javax.swing.JButton();
        jLabel_dados_do_cartao = new javax.swing.JLabel();
        jLabel_nome_titular = new javax.swing.JLabel();
        jTextField_nome_titular = new javax.swing.JTextField();
        jLabel_qtd_parcelas = new javax.swing.JLabel();
        jTextField_qtd_parcelas = new javax.swing.JTextField();
        jLabel_cod_seguranca = new javax.swing.JLabel();
        jTextField_cod_seguranca = new javax.swing.JTextField();
        jLabel_data_validade = new javax.swing.JLabel();
        jTextField_data_validade = new javax.swing.JTextField();
        jLabel_backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(590, 330));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 330));
        getContentPane().setLayout(null);

        jLabel_numero_cartao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_numero_cartao.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_numero_cartao.setText("Número do cartão:");
        getContentPane().add(jLabel_numero_cartao);
        jLabel_numero_cartao.setBounds(40, 50, 170, 22);
        getContentPane().add(jTextField_numero_cartao);
        jTextField_numero_cartao.setBounds(200, 50, 290, 30);

        jButton_Confirmar_dados.setBackground(new java.awt.Color(187, 222, 242));
        jButton_Confirmar_dados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Confirmar_dados.setForeground(new java.awt.Color(0, 0, 255));
        jButton_Confirmar_dados.setText("Confirmar dados");
        jButton_Confirmar_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Confirmar_dadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Confirmar_dados);
        jButton_Confirmar_dados.setBounds(340, 200, 150, 30);

        jButton_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar.jpg"))); // NOI18N
        jButton_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_voltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_voltar);
        jButton_voltar.setBounds(520, 10, 60, 60);

        jLabel_dados_do_cartao.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_dados_do_cartao.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_dados_do_cartao.setText("Dados do cartão:");
        getContentPane().add(jLabel_dados_do_cartao);
        jLabel_dados_do_cartao.setBounds(230, 10, 160, 22);

        jLabel_nome_titular.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_nome_titular.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_nome_titular.setText("Nome do titular:");
        getContentPane().add(jLabel_nome_titular);
        jLabel_nome_titular.setBounds(40, 100, 170, 22);
        getContentPane().add(jTextField_nome_titular);
        jTextField_nome_titular.setBounds(200, 100, 290, 30);

        jLabel_qtd_parcelas.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_qtd_parcelas.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_qtd_parcelas.setText("Qtd. de parcelas:");
        getContentPane().add(jLabel_qtd_parcelas);
        jLabel_qtd_parcelas.setBounds(40, 150, 140, 22);
        getContentPane().add(jTextField_qtd_parcelas);
        jTextField_qtd_parcelas.setBounds(200, 150, 40, 30);

        jLabel_cod_seguranca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_cod_seguranca.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_cod_seguranca.setText("Cód. de segurança:");
        getContentPane().add(jLabel_cod_seguranca);
        jLabel_cod_seguranca.setBounds(40, 200, 160, 22);
        getContentPane().add(jTextField_cod_seguranca);
        jTextField_cod_seguranca.setBounds(200, 200, 90, 30);

        jLabel_data_validade.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel_data_validade.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_data_validade.setText("Data de validade:");
        getContentPane().add(jLabel_data_validade);
        jLabel_data_validade.setBounds(250, 150, 150, 22);
        getContentPane().add(jTextField_data_validade);
        jTextField_data_validade.setBounds(390, 150, 100, 30);

        jLabel_backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tela3.png"))); // NOI18N
        getContentPane().add(jLabel_backgroud);
        jLabel_backgroud.setBounds(0, -30, 590, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void cadastraCartao(){        
        try {
        Fachada fachada = new Fachada();
        Cartao c = new Cartao();
        c.setCodPagamento(fachada.codigoPagamento());
        c.setNrCartao(jTextField_numero_cartao.getText());
        c.setNomeTitular(jTextField_nome_titular.getText());
        c.setDataValidade(jTextField_data_validade.getText());
        c.setCodSeguranca(jTextField_cod_seguranca.getText());
        if(jTextField_qtd_parcelas.getText() != null && jTextField_qtd_parcelas.getText().length() > 0){                
            c.setQuantidadeParcelas(Integer.parseInt(jTextField_qtd_parcelas.getText()));
        }                
        fachada.cadastrarCartao(c);
        aceito = true;
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
        }

        
        
    }
    private void jButton_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_voltarActionPerformed

    private void jButton_Confirmar_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Confirmar_dadosActionPerformed
        // TODO add your handling code here:
        cadastraCartao();
        if(aceito == true){
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton_Confirmar_dadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe_pgto_cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe_pgto_cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe_pgto_cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe_pgto_cartao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_pgto_cartao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Confirmar_dados;
    private javax.swing.JButton jButton_voltar;
    private javax.swing.JLabel jLabel_backgroud;
    private javax.swing.JLabel jLabel_cod_seguranca;
    private javax.swing.JLabel jLabel_dados_do_cartao;
    private javax.swing.JLabel jLabel_data_validade;
    private javax.swing.JLabel jLabel_nome_titular;
    private javax.swing.JLabel jLabel_numero_cartao;
    private javax.swing.JLabel jLabel_qtd_parcelas;
    private javax.swing.JTextField jTextField_cod_seguranca;
    private javax.swing.JTextField jTextField_data_validade;
    private javax.swing.JTextField jTextField_nome_titular;
    private javax.swing.JTextField jTextField_numero_cartao;
    private javax.swing.JTextField jTextField_qtd_parcelas;
    // End of variables declaration//GEN-END:variables
}
